permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: cxlove
  email: wenzhangcheng@hotmail.com
  link: cxlove.github.io
  weibo: http://weibo.com/orangeissweet
  github: http://github.com/cxlove
  facebook: https://www.facebook.com/profile.php?id=100007107877222&ref=tn_tnmn
  twitter: http://www.twitter.com/wenzhangcheng

# 站点信息
title: cxlove的博客
description: My personal blog
url: cxlove.github.io
rss_url: /pages/atom.xml

# gravatar头像及Favicon
gavatar: /public/img/cxlove.png
favicon: /public/img/cxlove.png

# google analytics 设置
ga:
  id: UA-55064621-1
  url: cxlove.github.io

# disqus 设置
disqus:
  shortname: cxlove

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - MachineLearning
  - Python

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档